#!/usr/bin/env bash
REPO_BASE=/mnt/shared/apt

EXPECTED_ARGS=2
E_BADARGS=64
if [ $# -ne $EXPECTED_ARGS ]; then
	echo "Usage: `basename $0` COMPONENT (stable|unstable) PACKAGE_NAME (customthingy4.0_4.0.1-MAINT-r999_all.deb)"
	exit $E_BADARGS
fi



COMPONENT=$1
PACKAGE_FILE=$2

reprepro -V --basedir ${REPO_BASE}/${REPOSITORY} --component ${COMPONENT} includedeb ${REPOSITORY} ${PACKAGE_FILE}
